### ISSUE TITLE
[GLib-GIO] Settings schema 'org.gnome.FontManager' is not installed

### ISSUE THREAD

**Issue by yuszuv** [FontManager/master#1]
I built the package on arch linux and now get this message, when I try to run it:

```
[WARNING 01:41:26] [GLib-GObject] The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
[WARNING 01:41:26] [GLib-GObject] The property GtkMisc:ypad is deprecated and shouldn't be used anymore. It will be removed in a future version.
[WARNING 01:41:26] [GLib-GObject] The property GtkAlignment:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
[WARNING 01:41:26] [GLib-GObject] The property GtkAlignment:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
[WARNING 01:41:26] [GLib-GIO] Settings schema 'org.gnome.FontManager' is not installed
[1]    18857 trace trap (core dumped)  font-manager
```

**Comment by JerryCasiano** [comment]
You don't say how you installed. But I'm guessing it wasn't the package at https://aur.archlinux.org/packages/font-manager-svn/

In any case, that error means that the schema was never installed/compiled, this is done during make install. So if you tried running it without installing or didn't install it system wide, that would probably explain it.

So, what steps did you use to install?

**Comment by JerryCasiano** [comment]
Opening this back up as a reminder. 

Allow running with settings from fallback directories or without saving settings (notify user).

**Comment by JerryCasiano** [comment]
Done in testing branch.
