### ISSUE TITLE
Alias settings

### ISSUE THREAD

**Issue by JerryCasiano** [FontManager/master#12]
Add preference pane for font aliases

**Comment by AnwarShah** [comment]
I second that. It's pretty important. but big Thanks for new UI.

**Comment by JerryCasiano** [comment]
Agreed. 

Sad thing is the basis for substitution has been there and working pretty much since I opened this issue. Unfortunately, I got hung up on details, how and how much to present to the user, and just set it down for a while. I'll try to get back to it soon, even if the first version is rough or a little limited compared to what Fontconfig actually allows.

Thanks for the feedback, glad to hear the UI is an improvement.

**Comment by JerryCasiano** [comment]
This feature is implemented in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by AnwarShah** [comment]
Thanks! It's great to hear. I'll test it

**Comment by AnwarShah** [comment]
I've tested it, successfully compiled and ran. I've tested substitution settings with 'sans-serif'. It worked.

On first run I had some links to the fonts which became invalid later in ~/.fonts directory. The program crashed with a message that the fonts cannot be opened. removing the invalid links fixed it.

**Comment by JerryCasiano** [comment]
> On first run I had some links to the fonts which became invalid later in ~/.fonts directory. The program crashed with a message that the fonts cannot be opened. removing the invalid links fixed it.

I'd like to understand what happened a little better, maybe reproduce it so I can at least try to fail gracefully rather than crash.

If you can explain what happened and how to reproduce, it would be very helpful.

**Comment by AnwarShah** [comment]
I tried to reproduce it by linking to some fonts in `.fonts` directory and then making them dangling link. But this time font-manager didn't crash.

I've found debian packaging problem which stopped at libfmcommon related message. I used `dpkg-buildpackage -b` command

**Comment by JerryCasiano** [comment]
> I've found debian packaging problem which stopped at libfmcommon related message. I used dpkg-buildpackage -b command

I haven't touched anything there yet so it's probably very broken.
I'll update the Debian folder before release.

At this point it's best if people don't install system wide since there is a lot of basics still missing. ;-)

**Comment by JerryCasiano** [comment]
Closing this out since the changes from testing have been merged into master.

Both the PPA and COPR repositories are up to date.
