### ISSUE TITLE
Help - Documentation

### ISSUE THREAD

**Issue by JerryCasiano** [FontManager/master#14]
Write help documents

**Comment by RalphCorderoy** [comment]
Documentation would be very helpful, ideally by fleshing out the existing man page.  A lot can be figured out by experimenting, e.g. unticking a font stops it appearing in gimp's list. But what about Collections? How are they expected to be used? Could I create one for gimp, say, without lots of the foreign-language fonts, and another for web browser that has all of them? Do I need to explicitly save Collections? I can see how to remove a font from a Collection, but how are they added in the first place? That's an example of the kind of thing that isn't obviously from poking around.

I suspect a lot of potential users give up and move on when font-manager(1) would suit their purposes, and a bit of documentation would be a fraction of the effort expended on the program so far.

**Comment by JerryCasiano** [comment]
> and a bit of documentation would be a fraction of the effort expended on the program so far.

Yet no one has stepped up to do it... 

In any case, to answer some of your questions, in case you haven't figured it out already.

Collections are completely virtual, you can create however many you like, they can overlap, they can be nested if you like. Their main purpose is to allow you to easily enable/disable groups of fonts all at once.
Collections are saved when the application closes, you don't need to do anything.
To add fonts, just drag and drop onto the collection. The collections view will reveal itself if you are dragging fonts over and switch back to category view once you're done. To reorder collections or nest them, just drag them around or into each other. 

You can also drag files onto the font list to install them.

You're right of course, some things aren't exactly obvious and should definitely be documented. However, I only have so much time. These days, the little time I can spend on it, gets spent on the plumbing which I'm not happy with and is far more important and interesting to me than writing help documents.

So, I guess what I'm saying is that if nobody else helps out in this regard there will probably not be any significant documentation till a 1.0 release. Sorry, but it is what is.

**Comment by stkurz** [comment]
I would be able and willing to contribute, but am still struggling to find out a lot of things as I just started using font-manager (on Fedora 26). 
A related question: Wouldn't it make sense to use github's wiki system for a collaborative effort for documentation?

**Comment by JerryCasiano** [comment]
Sure, we can do that. 

However, the actual help system uses Mallard and I would certainly prefer not to duplicate the work. Docs written in Mallard are easily translated to the web but not so sure about the other way around.

Mallard is pretty easy to write and you can do some really cool things with it. But it is tedious. :-(

http://projectmallard.org

As far as understanding the application well enough to write help documents, feel free to ask whatever, here or through email and I'll try to respond as best I can. ;-)

**Comment by Moilleadoir** [comment]
> The collections view will reveal itself if you are dragging fonts over and switch back to category view once you're done.

Wow, that is so unintuitive. I would _never_ have figured this out!

**Comment by JerryCasiano** [comment]
Help documents present in master.
