### ISSUE TITLE
Font activation problem

### ISSUE THREAD

**Issue by ImagineFabrique** [FontManager/master#15]
Thank you for this great application. Font-Manager is an 
essential tool to design on Linux!

Unfortunately i”ve seen a little bug.

when i add this font-family in font-manager https://www.cooperhewitt.org/wp-content/uploads/fonts/CooperHewitt-OTF-public.zip,
only the first font is activate, in my case heavy, light, thin and more, are not working at all. I have tested on different computer and it,s reproducible
It”s not the only one i have some other fonts that have the same problem

I”m using : 
Debian GNU/Linux stretch/sid 64 bits
Gnome Version 3.20.1
Font Manager 0.5.7

I hope it help.

**Comment by JerryCasiano** [comment]
Thanks for providing the link.

I'll have a look soon.

**Comment by JerryCasiano** [comment]
Oh wait...

I'm sorry, just realized you're using an unsupported version.

We're at 0.7.2 at this point and the 0.5 series has been deprecated for years.

Please test with the latest version and reopen this issue if the problem persists.

Unfortunate that Debian ships such an old version, you'll either needed to compile from source or build a Debian package yourself. There is a Debian folder in the repository that is used to build Ubuntu packages, that should work just fine.

git clone https://github.com/FontManager/master.git
cd master/debian
sudo apt-install devscripts
mk-build-deps control
sudo dpkg -i *.deb
debuild -us -uc

*should* work, that's of the top of my head and may needed adjustment though.

Thanks for your interest.

**Comment by JerryCasiano** [comment]
Also, just FYI the linked font files all appear to have the same weight? That will likely cause issues and not just for Font Manager.

**Comment by ImagineFabrique** [comment]
Thank you for your answers.
The FontManager’s latest update is pretty cool !

Effectively, 
this problem is in font-family not in font-manager.

After checking CooperHewitt in Fontforge, the issue is clear.
The font weight value is the same (700) for all weight.

I’ve modified this value for all weight and now,
it works !

**Comment by JerryCasiano** [comment]
Oh, good, you got it sorted.

Yeah, the new interface may take some getting used to and there are some features that are still missing. It will have all the features the previous version did at some point...

There is no documentation yet, so if you have any questions, don't hesitate to ask here.
