### ISSUE TITLE
Detect language?

### ISSUE THREAD

**Issue by ant-i-c-s** [FontManager/master#16]
Hi,

I have some Chinese fonts (and symbol ones) and they don't have normal latin characters, so I can't see a good preview (there are just boxes). Also, for some symbol ones, it's difficult to find what symbols it actually supports. A suggestion in character map mode would be to automatically jump to the section where there are the most characters, for example.

**Comment by JerryCasiano** [comment]
Indeed.

The character map currently uses the gucharmap library. It really doesn't do what Font Manager requires. Or in this case it actually does too much with no way to limit it to just what we want. Which makes it less useful.

Currently working on replacing that with an implementation of our own. One that only shows relevant categories, character counts, and of course only those characters which are actually in the selected font.

So yes, this is definitely something I also want to see and have started working towards, but it will take time. 

Thanks for your interest.

**Comment by JerryCasiano** [comment]
This feature is implemented in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by alerque** [comment]
1. Crikey that's a big commit. You know one of the best way to foster community contribution is to use granular commits on a development branch so eager adopters can follow along and help out right?

2. Lookin' good, this is definitely an improvement.

3. Right away what I noticed for Turkish is that the character viewer only shows the extended Latin characters used over and above the base Latin alphabet. These are certainly the most relevant characters to review when seeing _if_ the language is supported, but when reviewing a font I typically want to see the whole alphabet here. This view should include not just any characters unique to the language but the characters it uses in a base set as well.

4. The Turkish phase found in the code to be used in place of "The quick brown fox" doesn't seem to be used anywhere.

P.S. I'm happy to split this up and post more granular issues as well if that will help track the development process.

**Comment by JerryCasiano** [comment]
> Crikey that's a big commit. You know one of the best way to foster community contribution is to use granular commits on a development branch so eager adopters can follow along and help out right?

If anyone is actually interested in contributing they have yet to step up so it's really not even a consideration anymore.
That said, if someone was serious about helping out then of course they would be included in the process. ;-)

> Right away what I noticed for Turkish is that the character viewer only shows the extended Latin characters used over and above the base Latin alphabet. These are certainly the most relevant characters to review when seeing if the language is supported, but when reviewing a font I typically want to see the whole alphabet here. This view should include not just any characters unique to the language but the characters it uses in a base set as well.

Not sure about this. I'm going to kick this can down the road for now.

> The Turkish phase found in the code to be used in place of "The quick brown fox" doesn't seem to be used anywhere.

Yeah, about that...

So I'm realizing that attempting to " just do the right thing" is not a very good idea in this case. 

What willl end up happening is that we will default to Basic Latin everywhere,  "The quick brown ..."
We'll allow the user to select samples or preferred languages or something. 
Still trying to sort out the details on this.

Thanks you so much for checking it out and providing valuable feedback. 
Feel free to add any other thoughts here.

**Comment by JerryCasiano** [comment]
Closing this out as the changes have been merged into master and both PPA and COPR repositories updated.
