### ISSUE TITLE
Exo 2 does not install properly

### ISSUE THREAD

**Issue by Uglyface200** [FontManager/master#17]
Steps to reproduce:

1. Download and extract the font [Exo 2](https://fonts.google.com/specimen/Exo+2). It is available free of charge under the SIL Open Font License.
2. Install the light and regular styles through the Font Manager.

Expected behaviour: the light and regular styles co-exist.

Actual behaviour: the Regular Italic style of the typeface disappears, and the Regular style is displayed with a comma after it.

![screenshot_2016-07-12_14-00-30](https://cloud.githubusercontent.com/assets/2916723/16783522/3c56d2b8-4839-11e6-945b-f79f18382f80.png)

**Comment by JerryCasiano** [comment]
Please ensure that those font files are sane.

A lot of fonts have conflicting properties within the same family.

Run fc-query against the files and ensure that those values make sense.

Sounds like multiple faces have the same value somewhere. If that is the case, edit them with fontforge and they should work properly.

**Comment by JerryCasiano** [comment]
Oops. Didn't mean to close it.

I'll have a look later if the previous comment doesn't help.

**Comment by Uglyface200** [comment]
I just encountered this same issue with another typeface, [Fira Sans](https://fonts.google.com/specimen/Fira+Sans?query=fira), which had previously worked fine in version 0.5 (I'm using 0.7.3 on Xubuntu 16.04). It seems that when a light italic style is installed, the regular italic version is erased.

**Comment by JerryCasiano** [comment]
It seems that when a light italic style is installed, the regular italic version is erased.

That almost certainly means that they have conflicting values.

Just got home, I'll have a look in a few minutes.

**Comment by JerryCasiano** [comment]
Can't seem to reproduce this here...

![test]
(http://i.imgur.com/dOHZBiO.png)

Though I do note that Exo2 ExtraLight and Thin appear to have conflicting values.

**Comment by JerryCasiano** [comment]
I don't believe there are any changes in testing that would affect this, but not a hundred percent.

You can always build a debian package from testing to see if there's a difference.


    git clone https://github.com/FontManager/master.git
    git checkout testing
    cd master/build-aux
    make deb

**Comment by JerryCasiano** [comment]
Been a while without response. Going to assume this is an issue with the font files themselves.

Feel free to reopen if it's not.
