### ISSUE TITLE
Is really file-roller required?

### ISSUE THREAD

**Issue by slavkoja** [FontManager/master#2]
I tried to compile the latest font-manager release (v0.7.2) and it fails in configure phase with missing file-roller. I am on XFCE and i am using xarchiver and don't need/want to have another archive manager and configure --help nor README doesn't provides info how to disable it.

Please, it is really required?

BTW, i don't found requirements list in README nor in INSTALL file.

**Comment by JerryCasiano** [comment]
There is no code to handle the situation where file-roller isn't installed at this point. You can edit configure to remove the check but expect runtime errors.

Check configure.ac for dependencies.

**Comment by slavkoja** [comment]
:(

Thanks for explanation. I don't understand the code, then i cannot see details in code nor change it, but i consider it as bad idea to hardcode the exact external application, IMO especially when it as general purpose apps and not a library.

**Comment by JerryCasiano** [comment]
File Roller is by far the most common application of its type for GTK+ environments, it's also very light and has few requirements. On top of that it's the only one that provides a dbus interface.

There are reasons why it was chosen. 

I'm sure someone out there doesn't want to install the Gucharmap library because they don't need a character map, someone else doesn't want to install json-glib, so on and so forth. Should I spend the little free time I have making everything optional to please just a few users? 

That seems like a bad idea to me.  ;-)

**Comment by JerryCasiano** [comment]
So, as I often do, I've changed my mind on this...

Leaving this open, I really do have little time to dedicate to this so it'll probably be a while.

But I agree, the font-manager command should be modular, extensible, and generic. Different front ends should be able to attach, plugins, etc. Certain features available conditionally.

So congratulations, you've just set off another rewrite, in the middle of a rewrite. Yo dawg...

**Comment by JerryCasiano** [comment]
Fixed in master. File Roller is optional.

Since making the application more modular is a long term goal and not what this issue was about, closing.

**Comment by slavkoja** [comment]
Thanks ;-)

**Comment by AnwarShah** [comment]
I just read this thread. I really love the mount of <3 you put on this project. But Since it became optional, How do I enable the file-roller integration?

**Comment by JerryCasiano** [comment]
If you're building from source pass --with-file-roller to ensure support is
compiled.

It was previously detected at build time but was changed on request by the
Debian maintainer to make packaging easier. This applies to the latest
release and master. This is temporary, in the future we'll move to either
using libarchive directly or detecting if file-roller is installed at
runtime.

HTH
