### ISSUE TITLE
Can't resize top and left side is chopped off.

### ISSUE THREAD

**Issue by Fleuv** [FontManager/master#20]
Have a look at the screen shot below.

![font-manager-gui-bug](https://cloud.githubusercontent.com/assets/5595936/17985292/7950b6bc-6b15-11e6-81af-f8548fa820a5.png)

After restarting the program I'm able to get top the top again but the side is still chopped off. But I managed to drag the program window under my ubuntu top bar some how.
```
$ uname -a
Linux 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JerryCasiano** [comment]
You should file that with Ubuntu.

Font Manager doesn't control anything at that level.

**Comment by JerryCasiano** [comment]
Also, holding down alt while clicking anywhere in the window should allow you to move it.

HTH
