### ISSUE TITLE
Suggestion: Fonts default to "disabled" when new font directory added.

### ISSUE THREAD

**Issue by thatchermo** [FontManager/master#21]
I apologize in advance if an issue isn't the correct way to make contact with the project, but I wanted to say thanks for writing this code and offer two suggestions (one per issue).

The first suggestion has to do with what happens when you add a font directory. My use case is that I've got a lot of font files stored in a separate font directory structure, and I'm looking to use the font manager to preview them and selectively activate them when I need them. 

I began writing this issue based on version 0.5.7-4 in Ubuntu 16.04, but decided to try the latest version in the ppa as well (0.7.3~201606250139~ubuntu16.04.1). The latest version is nice in that the entire directory is not activated by default when you add a source, but when I click the slider to turn a directory "On," it's the case that all fonts in that directory all get activated at once. It would be nice to turn the directory on, but still have individual fonts default to deactivated until they're specifically selected. Otherwise, once I turn a directory "On" in the Preferences pane, I have a big job of deactivating each individual font.

Thanks again for your work on this project!

**Comment by JerryCasiano** [comment]
I don't think I'm going to do this. At least not by default.

Here's why. 
Seems like a limited use case, I think most people would expect the current behavior and I get the feeling then I would get the opposite complaint, that having to enable every single font in a folder is tedious.
It would also mean adding all the fonts in every source to the reject file and then having to keep track of whether they're even around or just letting the file grow and grow, not good.

Also, at this point my time is very limited and there is still too many other basics that aren't there yet.

But I have been known to change my mind.
