### ISSUE TITLE
Suggestion: Actions on a per-file, not per-family basis

### ISSUE THREAD

**Issue by thatchermo** [FontManager/master#22]
One issue that I noticed when using font-manager is that it only allows activation/deactivation/adding to a collection on a per-family basis. In an ideal world, this would be great, but it does cause a few problems in  practice for my workflow. The problem occurs because other software is not always great at handling the large number of separate styles that some families include (for example, many Adobe fonts have light, black, semibold weights along with the standard four). Libreoffice has in the past been confused when there are too many weights available, and I've also noticed that XeTeX is choosing inappropriately from time to time. My previous solution had always been to only activate a subset of weights that I knew the software could handle correctly, but that wouldn't be an option if using font-manager.

Again, thanks for your work.

**Comment by JerryCasiano** [comment]
I considered doing this. But quite honestly I don't feel that the benefits outweigh the complexity that it adds.

It's definitely something that's been on my list of wants and 1.0 is pretty far out so I'll definitely revisit it later on.

Thanks for the feedback.

**Comment by JerryCasiano** [comment]
Closing this out as I still don't believe the pros outweigh the cons in this case.
