### ISSUE TITLE
FTBFS in Debian unstable

### ISSUE THREAD

**Issue by alessio** [FontManager/master#24]
As per the [original bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839350), font-manager failed to build on Debian unstable :

> 
> Hi,
> 
> During a rebuild of all packages in sid, your package failed to build on
> amd64.
> 
> Relevant part (hopefully):
> > make[2]: Entering directory '/<<BUILDDIR>>/font-manager-0.7.2+0git410aa802/lib'
> > `/usr/bin/pkg-config --variable=glib_compile_resources gio-2.0` \
> > --sourcedir=../data \
> > --generate-source \
> > --target=FontManagerGResource.c \
> > ../data/FontManagerGResource.xml
> > rm -f libfontmanager_la_vala.stamp && echo stamp > libfontmanager_la_vala.stamp-t
> > CDPATH="${ZSH_VERSION+.}:" && cd . && /usr/bin/valac --target-glib 2.38 --pkg gmodule-2.0 --pkg glib-2.0 --pkg gio-2.0 --pkg gtk+-3.0 --pkg gee-0.8 --pkg json-glib-1.0 --pkg Gucharmap-2.90 --pkg libxml-2.0 --pkg pango --pkg sqlite3 -D HAVE_FILE_ROLLER --gresources ../data/FontManagerGResource.xml --library fontmanager -H fontmanager.h  -C Common/About.vala Common/ArchiveManager.vala Common/Cacheable.vala Common/Collections.vala Common/Constants.vala Common/Database.vala Common/FontData.vala Common/FontInfo.vala Common/JsonWriter.vala Common/Logger.vala Common/Settings.vala Common/Utils.vala Filters/Category.vala Filters/Collection.vala Filters/Disabled.vala Filters/Filter.vala Filters/SearchResult.vala Filters/Unsorted.vala FontConfig/Alias.vala FontConfig/Common.vala FontConfig/Directories.vala FontConfig/Enums.vala FontConfig/Families.vala FontConfig/Family.vala FontConfig/Font.vala FontConfig/MonitoredFiles.vala FontConfig/Properties.vala FontConfig/Selections.vala FontConfig/Sources.vala FontConfig/XmlWriter.vala Glue/Glue.vala Library/Install.vala Library/Library.vala Library/Query.vala Library/Remove.vala Library/Sorter.vala UX/CharacterMap/CharacterDetails.vala UX/CharacterMap/CharacterMapSideBar.vala UX/CharacterMap/CharacterTable.vala UX/Controls/BaseControls.vala UX/Controls/CollectionControls.vala UX/Controls/FontListControls.vala UX/Controls/PreviewControls.vala UX/FontConfig/Controls.vala UX/FontConfig/DisplayPropertiesPane.vala UX/FontConfig/FontPropertiesPane.vala UX/FontConfig/FontSourceList.vala UX/FontConfig/PreferencePane.vala UX/FontConfig/SubpixelGeometry.vala UX/FontConfig/Substitute.vala UX/Metadata/Description.vala UX/Metadata/License.vala UX/Metadata/Properties.vala UX/Metadata/Title.vala UX/Models/CategoryModel.vala UX/Models/CollectionModel.vala UX/Models/FontModel.vala UX/Models/UserFontModel.vala UX/Trees/CategoryTree.vala UX/Trees/CollectionTree.vala UX/Trees/FontListTree.vala UX/Trees/UserFontTree.vala UX/Utils/Color.vala UX/Utils/FileSelector.vala UX/Utils/Utils.vala UX/Views/FontPreviewPane.vala UX/Widgets/CellRendererPill.vala UX/Widgets/Controls.vala UX/Widgets/Labels.vala UX/Widgets/TextViews.vala UX/Widgets/TreeViews.vala
> > Common/Cacheable.vala:37.5-37.42: error: overriding method `Cacheable.find_property' is incompatible with base method `Json.Serializable.find_property': incompatible return type.
> >     public unowned ParamSpec find_property (string name) {
> >     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > Compilation failed: 1 error(s), 0 warning(s)
> > Makefile:2113: recipe for target 'libfontmanager_la_vala.stamp' failed
> > make[2]: *** [libfontmanager_la_vala.stamp] Error 1
> 
> If the failure looks somehow time/timezone related:
> Note that this rebuild was performed without the 'tzdata' package
> installed in the chroot. tzdata used be (transitively) part of
> build-essential, but it no longer is. If this package requires it to
> build, it should be added to build-depends. For the release team's
> opinion on this, see
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836940#185
> 
> The full build log is available from:
>    http://aws-logs.debian.net/2016/09/30/font-manager_0.7.2+0git410aa802-3_unstable.log
> 
> A list of current common problems and possible solutions is available at
> http://wiki.debian.org/qa.debian.org/FTBFS . You're welcome to contribute!
> 
> About the archive rebuild: The rebuild was done on EC2 VM instances from
> Amazon Web Services, using a clean, minimal and up-to-date chroot. Every
> failed build was retried once to eliminate random failures.
>

**Comment by JerryCasiano** [comment]
Thanks for the heads up.

https://github.com/GNOME/vala/commit/28fa5311c35522e9ade4b101fb4c81401d01f18a

A fix in the bindings seems to be the cause. 

I'll try to get to this soon, over the weekend more than likely. It looks like it simply needs to be marked nullable and the vala version bumped.

**Comment by JerryCasiano** [comment]
Feel free to reopen if new release doesn't solve the issue.

Thanks again.
