### ISSUE TITLE
Font-manager uses 100% CPU.

### ISSUE THREAD

**Issue by fubarbaz** [FontManager/master#27]
See: https://github.com/NixOS/nixpkgs/issues/21522

**Comment by JerryCasiano** [comment]
Sorry, but I can't seem to reproduce this on either Fedora 25 or Ubuntu 16.10 even with a fresh profile. 

I'm not very familiar with NixOS but from what I understand about it I'm inclined to believe this is unique to your particular installation/configuration, at least until other users chime in with the same problem.

In any case, as I said I'm not very familiar with it so if it is something specific to NixOS it's not really something that I can address anyway, users will need to assist with debugging/fixing this issue.

I would however suggest addressing the warnings generated by Gtk+ and seeing if that has any effect.
