### ISSUE TITLE
Specify minimum GTK version

### ISSUE THREAD

**Issue by quassy** [FontManager/master#3]
My guess is the program has a minimum requirement for the GTK version (or will it run with 3.0?), so it should be written down somewhere for people to check before attempting to install.

**Comment by JerryCasiano** [comment]
Minimum required version is 3.12 at this point. 

configure.ac lists all requirements for those building from source.

Most users should use available packages.

Sorry, but I used to list requirements in the readme, then people wanted me to list package names for their specific distribution... Yeah.
