### ISSUE TITLE
No close button on gnome 3.20

### ISSUE THREAD

**Issue by Talor-A** [FontManager/master#31]
Using the latest FontManager build, there is no close button on the window as ther gtk apps have (nautilus and tilix shown in screenshot). this occurs using adwiata and other themes as well.

![see here](https://cloud.githubusercontent.com/assets/11509865/24732075/53e5fad2-1a23-11e7-941a-960d1512d58f.png)

**Comment by JerryCasiano** [comment]
Do you have a quit option in both menus?
You should also be able to Ctrl+q
Plus the window menu itself.

So that's four ways to quit.

I kind of consider it redundant, I could see an argument for consistency but...  not sure I consider it a bug.

**Comment by Talor-A** [comment]
Yes this is just more of a suggestion for improvement than an actual problem. There are obviously several ways to close the window, but not including the standard close button breaks the pattern followed by most other GTK3 apps.

**Comment by JerryCasiano** [comment]
It's not really something that I'm interested in "fixing", sorry. 

I chose not to include those buttons. I personally prefer the look of the current HeaderBar. ;-)
And considering this is the first time it's been brought up that decision doesn't appear to bother many.

That being said, if someone wants to patch in the option to display the standard controls I'll be happy to merge the changes, so long as it's an option in preferences I'm fine with it being the default even. 

That part of the code probably won't need to change much in the future anyway.

I'll leave this open for now in case anyone wants to address it.

**Comment by Talor-A** [comment]
Thanks for the feedback, I understand why you want it the way it is. If I have time I'll try to send a PR to make it an option.

**Comment by RalphCorderoy** [comment]
I too wondered where the Close button was, and ended up opening the window manager's menu and selecting Close. I also found its own title bar annoying as when it's busy it doesn't respond to dragging, unlike the window manager's re-parenting title bar that doesn't care what the process is tied up with.

**Comment by JerryCasiano** [comment]
You can always disable CSD in the preferences if it's not to your liking. 

That will give you normal decorations. ;-)

**Comment by JerryCasiano** [comment]
This suggestion is implemented in the testing branch and will become part of 0.7.4

Thanks.
