### ISSUE TITLE
Vala

### ISSUE THREAD

**Issue by iandoug** [FontManager/master#37]
Hi
Trying to install on Gentoo. 
./configure complains about Vala, but I have it installed. 
Tried both 0.73 and master-master.

configure: error: 
            Build requirements (valac) were not met:
            Please install Vala >= 0.28 and try again.
            https://wiki.gnome.org/Projects/Vala
            
trooper font-manager-0.7.3 # eix vala
[I] dev-lang/vala
     Available versions:  
     (0.32) 0.32.1
     (0.34) 0.34.7 0.34.8
       {test}
     Installed versions:  0.34.8(0.34)(09:42:32 17/05/2017)(-test)
     Homepage:            https://wiki.gnome.org/Projects/Vala
     Description:         Compiler for the GObject type system

[I] dev-libs/vala-common
     Available versions:  0.32.1 0.34.7 0.34.8
     Installed versions:  0.34.8(14:55:15 16/05/2017)
     Homepage:            https://wiki.gnome.org/Projects/Vala
     Description:         Build infrastructure for packages that use Vala

Thanks, Ian

**Comment by JerryCasiano** [comment]
Make sure that

    which valac
    valac --version

Both return something sane.

**Comment by iandoug** [comment]
Mmm okay now for some reason which only the Gentoo wizards will know, I have

trooper ~ # which valac
which: no valac in (/sbin:/bin:/usr/sbin:/usr/bin)
trooper ~ # which valac-0.34
/usr/bin/valac-0.34

trooper ~ # valac-0.34 --version
Vala 0.34.8

**Comment by JerryCasiano** [comment]
Do a quick symlink from that binary to just valac in order to solve the compile then ask why.

 ;-)

**Comment by iandoug** [comment]
Thanks, that worked, though also had to install libgee.
Don't know why it's not in portage (so no maintainer... they'll probably tell me to become the maintainer, or else they may be some licence issues...) ... I'm quite impressed. Just puzzled by the lack of window decoration (I'm on KDE).
Good job :-)

**Comment by JerryCasiano** [comment]
Glad you got it sorted.

BTW, you can disable CSD in preferences, that should give you the normal decorations if you're using an environment that doesn't support CSD well.

**Comment by iandoug** [comment]
Ah. I had it on "because I wanted the normal window decorations" ... so clearly your understanding of the option description is the opposite of how I understood it... :-)
Working now.

Some other issue:
1. Sources. At present I have .fonts and fonts-master (local copy of Google's font collection) defined. However when I go to the settings page both are set Off, even though the fonts show up in the list. I've tried to add another folder with other fonts, but it refuses to accept it. Is there a limit of 2 folders, or am I doing something wrong?
Google fonts is at /home/ian/fonts-master, and I want to add
/home/ian/fonts ..... so I can't see any difference in permissions/paths/whatever ...

Will put other issues in different thread.

**Comment by JerryCasiano** [comment]
There are no limits to the number of sources. Not sure why it wouldn't allow you to add it. Running the application from the command line using the -D switch might tell us something useful, maybe.

Sources are off by default, they are always enabled for the application itself so that you can view them but not for the rest of the system. Enabling a source makes it available to other applications, all the fonts in that source will appear as installed.

**Comment by iandoug** [comment]
Okay, now I am a bit thoroughly confused.
My understanding is this:
1. "Sources" is a list of folders that Font-Manager consults to find fonts on the system.
2. I thought that putting it "On" meant "actually use this folder". But you say it actually means "expose this folder to the system and install all the fonts". Am I correct so far?

I tried again to add a folder, the same way as I added /home/ian/fonts-master, by clicking the "+" sign on the Sources page, navigating to the folder, and clicking Open on the dialogue.

Still no joy.

So then (in what was probably a mistake) I clicked the "+" (Add fonts) from outside settings and selected the same folder.... FM then went away for a bit and loaded a whole bunch of fonts, which now appear to be added to the system (which is NOT what I wanted...:-) )

Observations: 
1. previously, under "User",  the font count was zero. Now it is not. This is curious because there's currently a bug in KDE, where if you use KDE font management interface for installing a font, and select "System" as opposed to "Personal", it hangs. So lately I have avoided that by installing new fonts as "Personal", so I was surprised that FM said the Personal count was zero. This could be some issue between how KDE works compared to Gnome and derivatives?

2. I'm trying to figure out exactly which fonts got added... does FM unpack archives or just look for plain .ttf/.otf/etc/ files when adding?

3. even though /usr/share/fonts is not listed in the "sources", it appears fonts from there are detected.

4. I assume the "-" (remove fonts) process just removes them as "installed" and does not delete source files? Bit hesitant to find out the hard way :-)

thanks, Ian

**Comment by iandoug** [comment]
Relevant bits:
[DEBUG 11:31:24] [Main:309] Font Manager 0.7.3
[DEBUG 11:31:24] [Main:310] Using GLib 2.50.3
[DEBUG 11:31:24] [Main:311] Using JSON-GLib 1.2.8
[DEBUG 11:31:24] [Main:312] Using SQLite 3.17.0
[DEBUG 11:31:24] [Main:313] Using FontConfig 2.11.01
[DEBUG 11:31:24] [Main:314] Using Pango 1.40.5
[DEBUG 11:31:24] [Main:315] Using GTK+ 3.22.15
[DEBUG 11:31:24] [Main:317] Screen is composited. Client side decorations enabled.
[DEBUG 11:31:24] [Main:321] Running on KDE
[DEBUG 11:31:24] [Sources:266] Loading source : /home/ian/fonts-master
[DEBUG 11:31:24] [Sources:266] Loading source : /home/ian/.fonts
[DEBUG 11:31:24] [Selections:122] Add selection : dir : /home/ian/fonts-master
[DEBUG 11:31:24] [Selections:122] Add selection : dir : /home/ian/.fonts
[DEBUG 11:31:24] [FontPreviewPane:148] Selected preview mode : Preview
[cut]

[DEBUG 11:31:25] [Database:95] Starting database synchronization : Font table
[DEBUG 11:31:25] [Database:135] Database synchronization complete : Font table
[DEBUG 11:31:27] [FontListTree:168] Selected font : .
[DEBUG 11:31:27] [GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
[DEBUG 11:31:27] [GdkPixbuf]    Encoding raw
[DEBUG 11:31:27] [GdkPixbuf]    Dimensions: 14 x 14
[DEBUG 11:31:27] [GdkPixbuf]    Rowstride: 56, Length: 808
[DEBUG 11:31:27] [GdkPixbuf]    Copy pixels == false
[DEBUG 11:31:27] [GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
[DEBUG 11:31:27] [GdkPixbuf]    Encoding raw
[DEBUG 11:31:27] [GdkPixbuf]    Dimensions: 14 x 14
[DEBUG 11:31:27] [GdkPixbuf]    Rowstride: 56, Length: 808
[DEBUG 11:31:27] [GdkPixbuf]    Copy pixels == false
[DEBUG 11:31:31] [State:218] Restoring previous selection for CollectionTree :: 0
[DEBUG 11:31:31] [State:220] Ignoring non-existent path : 0
[DEBUG 11:31:31] [State:218] Restoring previous selection for CategoryTree :: 11
[DEBUG 11:31:31] [FontListTree:168] Selected font : .
[DEBUG 11:31:31] [CategoryTree:125] Selected category : Unsorted
[DEBUG 11:31:31] [State:218] Restoring previous selection for FontList :: 0

**Comment by JerryCasiano** [comment]
> "Sources" is a list of folders that Font-Manager consults to find fonts on the system.

No, Font Manager uses Fontconfig to find fonts available on the system.

Sources are additional places you would like Font Manager to load fonts from.
They are intended to make it easy to preview a folder of fonts and add/remove said folder from the Fontconfig configuration as needed without changing its location or permanently installing the files in it.

e.g. say you have a Windows installation, you could add the font folder from your Windows installation in Sources and enable the source in order to have all those font files available to you without copying them over.

> I thought that putting it "On" meant "actually use this folder". But you say it actually means "expose this folder to the system and install all the fonts".

Toggling it "On" does mean actually use this folder.

Until the Source is toggled on it is only available to the application, once it is toggled on it gets added to the Fontconfig configuration. Adding/Removing a directory from the Fontconfig configuration is for all intents and purposes equal to installing/uninstalling all the font files in that directory, the only difference is the files stay wherever they are.

> I'm trying to figure out exactly which fonts got added... does FM unpack archives or just look for plain .ttf/.otf/etc/ files when adding?

By default Font Manager will recursively search for and install all fonts in the selected folder and this includes extracting any archives found.

BUT it does need to have been built with support for file-roller and file-roller must be installed for that to happen otherwise it will skip archives.

> I assume the "-" (remove fonts) process just removes them as "installed" and does not delete source files? Bit hesitant to find out the hard way :-)

Nope, if you installed the fonts using Font Manager those files will have been copied to and organized in ~/.local/share/fonts which is the default user font directory. If you remove fonts using Font Manager those files will be deleted.

The original file wherever it's at should not be affected.

.

By the way, I can duplicate the issue with adding Sources. I'll try to have a look.

**Comment by JerryCasiano** [comment]
The latest commit *should* resolve the issue you were originally having with adding Sources.

If you could test and verify it works for you, it would be much appreciated.

**Comment by iandoug** [comment]
Looks like it's working now, thanks. I had previously edited the Sources.xml file by hand and it picked it up (and did not appear to overwrite it immediately). But then I deleted the folder and re-added and seems to work as advertised.

I also installed file-roller before I re-installed but it did not seem to include it automagically in the compilation. 
I tried ./configure --with-file-roller as well but that didn't seem to work either. Maybe I needed a make clean first? Not very clued up on such things, Portage normally takes care of it.

**Comment by JerryCasiano** [comment]
Sure thing.

Hopefully my previous explanation helped a little.

As far as archive support goes, installing file-roller and running configure the way you did should have enabled it. And it should have shown Archive support = yes at the end of running the configure script. 

Have you tried dragging an archive onto the font list or selecting one from the add dialog?
If so, what happens? Does it print anything in terminal when it falls?

**Comment by iandoug** [comment]
I redid the install (make clean, autogen with --with-file-roller, etc)
If I drag an archive onto the file list (in Manage view) it unpacks and adds it.
But it's not automatically checking inside all the archives in one of my Source folders.

The part "after unpack" where it rebuilds the list takes a while.

**Comment by JerryCasiano** [comment]
> But it's not automatically checking inside all the archives in one of my Source folders.

No, that's​ not something it even tries to do.
We could probably do it, it's just not something we currently do. 

> The part "after unpack" where it rebuilds the list takes a while.

Yeah, that typically depends on the amount of fonts installed. But it's something that will likely improve in future versions.
