### ISSUE TITLE
Sorting....

### ISSUE THREAD

**Issue by iandoug** [FontManager/master#38]
Hi

Is it possible to automagically detect if a font is Serif or Sans Serif?

I think it would be useful if fonts could be categorised into more-or-less the "accepted" categories (which AFAIK is not Settled Science...) but at least into things like Serif, Sans Serif, Script, Dingbats/ornamentals, etc. 

If not automagically then perhaps via something like "tags" or "keywords" where the user could manually define categories and allocate fonts to them. This is something different to "collections" or should collections be used for this?

Thanks, Ian

**Comment by JerryCasiano** [comment]
Is it possible to automagically detect if a font is Serif or Sans Serif?

It's possible for those that provide accurate Panose information, which are in the minority. For all others we could guess based on style name.

I think the best solution is something like "smart" collections.

This is a low priority though. Too many other basics still missing. 

So for now, yes, use collections. You can always nest them.

**Comment by iandoug** [comment]
Guess my comment on other thread belongs here.

**Comment by JerryCasiano** [comment]
Closing this out as I still don't see any reliable way to classify fonts as suggested.
