### ISSUE TITLE
Database insert problem

### ISSUE THREAD

**Issue by iandoug** [FontManager/master#40]
The famous apostrophe problem. I fight with it too.. 

[DEBUG 14:45:02] [Main:245] Updating font configuration
[WARNING 14:45:14] [Category:48] Nick's Fonts category results invalid
[FATAL 14:45:14] [Category:49] Database error : SQLite : (prepare_v2) [1] - near "s": syntax error
[FATAL 14:45:14] Font Manager will not function properly.
[DEBUG 14:45:18] [CategoryTree:125] Selected category : Slant
[DEBUG 14:45:19] [FontListTree:168] Selected font : .

**Comment by iandoug** [comment]
Some more (I rebuild font cache both as root and user, fc-cache -rv, which seems to have helped speed up font-manager.

[WARNING 15:56:02] [Pango] pango_layout_set_markup_with_accel: Error on line 1 char 30: Invalid UTF-8 encoded text in name - not valid '� Systematic -BRK-'

[FATAL 15:54:35] [Gtk] gtk_tree_model_get_iter_from_string: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed
[FATAL 15:54:35] Font Manager will not function properly.
[DEBUG 15:54:35] [State:218] Restoring previous selection for FontList :: 0
[FATAL 15:54:35] [Gtk] gtk_tree_store_iter_is_valid: assertion 'GTK_IS_TREE_STORE (tree_store)' failed
[FATAL 15:54:35] Font Manager will not function properly.
[DEBUG 15:54:35] [State:220] Ignoring non-existent path : 0

Getting a lot of those Pango layout editors ... all seem the same.

**Comment by JerryCasiano** [comment]
Ugh. I really need to have test cases for this...

I've fixed and reintroduced this issue more than once.

I'll see if I can get to this later today. If not, it'll be the weekend.

Thanks.

**Comment by iandoug** [comment]
Don't know where the problem is. When it surfaced the first thing I did was 
locate -i nick
but that turned up nothing relevant ... but redid it again now slightly differently and think I found the font, screenshot attached.
![spectacle j13076](https://user-images.githubusercontent.com/12673886/27839701-a3054944-60f3-11e7-8f50-e3e1eaa0d320.png)

**Comment by JerryCasiano** [comment]
Perfect.

Thank you.

**Comment by JerryCasiano** [comment]
Closing this out as this is no longer an issue in master.
