### ISSUE TITLE
Properties lacks path to the font 

### ISSUE THREAD

**Issue by m0t0rh34d** [FontManager/master#42]
Hello! It would be really handy if there was an option to see the path to the font. Sometimes it really hard to find where it lies. Thanks for the attention!

**Comment by JerryCasiano** [comment]
Someone else requested the same thing.

Not sure exactly when it'll get done but it will get done.

I think it'll end up being in a right click menu on the font list. I'm thinking of having "Show in folder" and "Copy Location" entries.

Would that help with your use case?

**Comment by m0t0rh34d** [comment]
Yes thank you very much for your reply. I'm not so well acquainted with the C
 otherwise I wouldn't bother you. I think this is an important feature and will enhance font manager a little bit.

**Comment by JerryCasiano** [comment]
It's no bother.  If I wasn't reworking the lower layers a little bit I could probably commit the change today but since a lot is going to change it doesn't seem like a good idea to spend time on the UI right now.

In any case, it will get done for sure. Soon, I hope. :-)

**Comment by JerryCasiano** [comment]
This feature is implemented in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

Right clicking in font list allows copying file location or opening folder.

**Comment by JerryCasiano** [comment]
Closing this out since these changes are now in master and both the PPA and COPR repositories are up to date.

Thanks for your suggestion.
