### ISSUE TITLE
Browse mode: Filter by multiple categories

### ISSUE THREAD

**Issue by krlmlr** [FontManager/master#43]
e.g., I want to browse all regular monospace fonts installed on my system. On 17.04, I can either show all monospace fonts or all regular fonts, but not filter by both criteria. Is this already implemented in the development version by any chance?

**Comment by JerryCasiano** [comment]
> Is this already implemented in the development version by any chance?

No. You'll be able to do this once search is implemented but it is a very low priority for me at this point. Sorry.

**Comment by krlmlr** [comment]
Thanks, looking forward to it.
