### ISSUE TITLE
Preview Pane can mismatch the currently selected font

### ISSUE THREAD

**Issue by MostlyUpward** [FontManager/master#46]
The Preview Pane can be dangerous - it consistently previews a font other than the one I just clicked, for about 2-15 seconds, on a 2015-era high-end notebook computer. I have 15,000+ fonts in my "Sources" so there is likely extra lag from that, but that is also not an uncommon amount for people who work with type. During my normal workflow, if I am trying to select a font, it is often done with lots of Alt+Tab'ing and split-second glimpses and actions, whenever possible. The current design of this program (which is great, of course) completely torpedoes that kind of process for me, unfortunately.

I would say the application needs either instant updates in the Preview Pane (so that it is 100% reliable at all times) or to at least include the currently previewed font's name, so that the program either acts as a true WYSIWYG interface as it clearly intends to be, or at least lets me know when I need to wait a couple of seconds.

Thank you for a great program!

**Comment by JerryCasiano** [comment]
Dangerous? Really? 

> I would say the application needs either instant updates in the Preview Pane (so that it is 100% reliable at all times) or to at least include the currently previewed font's name, so that the program either acts as a true WYSIWYG interface as it clearly intends to be, or at least lets me know when I need to wait a couple of seconds

I would say you need to write the code that accomplishes this. 

Font Manager is intended for average desktop users and they don't typically have fifteen thousand fonts. It's not a use case I'm interested in. So if you want to do the work, great, other than that it will likely never be suitable for your needs.

Good luck.

**Comment by stkurz** [comment]
> Font Manager is intended for average desktop users and they don't typically have fifteen thousand fonts. It's not a use case I'm interested in.
The thing is that there's not a whole lot of alternatives available, so it's natural for users coming from other OSes to ask for solutions that can be seen somewhere else. I remember when Extensis Suitcase X came out it had similar problems, and it took them some time to address them properly (giving FontExplorer a chance to gather a growing user base) although they – as opposed to Font Manager, which is maintained by just one person – might have had the resources. That said, I might second all wishes for 15k, 20k, 25k active font sources, but it's clear that that's just not realistic at the moment…

**Comment by JerryCasiano** [comment]
> The thing is that there's not a whole lot of alternatives available, so it's natural for users coming from other OSes to ask for solutions that can be seen somewhere else.

Oh, I understand that. But sometimes the tone of the request just cracks me up. 

> That said, I might second all wishes for 15k, 20k, 25k active font sources, but it's clear that that's just not realistic at the moment…

Correct.

It's not that I'm actively against improving the application to that point, not at all. 
I just want to be clear that it may get there eventually or it may not.
There are so many other things that are simply missing or that I feel need to be addressed before this that it's just not something that's worth even this discussing at this point.
