### ISSUE TITLE
Non-English preview troubles

### ISSUE THREAD

**Issue by kitaets** [FontManager/master#47]
I used Font Manager from the official Ubuntu repository, **it worked OK**, but it was very old (v.0.5.x). I just installed v.0.7.3 and have strange problem with **some** fonts. Every font I have is usable for cyrillic text, but Font Manager shows some fonts like they have different codepage. Furthermore, when Font Manager starts, it shows cyrillic letters for a second but then it changes to the wrong codepage. The same fonts look OK in LibreOffice, in Inkscape and in Font Manager from the official Ubuntu repository.

_Update: I wrote this about Ubuntu 16.04 (x64), and now I've got the same issue in fresh Xubuntu 16.04 (x32)._

**start**
![start](https://user-images.githubusercontent.com/34854461/34352034-2d6506c6-ea31-11e7-96e8-b5ed284fc62c.png)

**2 seconds after start**
![2 seconds after start](https://user-images.githubusercontent.com/34854461/34352043-35bc275a-ea31-11e7-934b-ea25d09acf51.png)

**compare**
![compare](https://user-images.githubusercontent.com/34854461/34352046-3aec90ac-ea31-11e7-9cb3-e937d40fcbfa.png)

**libreoffice**
![libreoffice](https://user-images.githubusercontent.com/34854461/34352050-3fc3a3d6-ea31-11e7-9f51-c94846019352.png)

**Comment by JerryCasiano** [comment]
Interesting.

Especially the part where it's right at first but then changes, thanks for mentioning that it's very helpful. I'll have a look over the weekend and see what I find.

Will likely need your help to confirm.

Really, our support for non Latin languages is, well we don't have any yet. But it's something I want to have working properly for sure.

**Comment by JerryCasiano** [comment]
Hmm. This issue might be somewhere else in the stack.

I'm getting some strange results but only with one font, Abyssinca SIL

Are you seeing this with other fonts as well?

**Comment by JerryCasiano** [comment]
Hmm...

Looks like this may be somewhere else in the stack.
Attempting to render that pangram using Abyssinica SIL in other applications which use Pango gives the same result.

LibreOffice uses its own rendering method, as far as I know.

Do other GTK+ applications render these fonts properly for you?

**Comment by kitaets** [comment]
**Bingo!**
This problem exists for those fonts, what don't have needed symbols. If you try the Kacst fonts family, you will see the same issue for latin symbols. Other apps just use standart font to show non-existed symbols, what is good to read a text, but is not good for font management or design apps. So your app works properly for cyrillic letters. But the app makes confusion because it shows letters on the start. And I'm not shure that Font Manager treats properly such fonts as **Dingbats** and **Kacst**. It does not show symbols.

**Comment by JerryCasiano** [comment]
I think the reason you initially see characters is because when that widget is initialized it's set to the default system font then once the program loads completely it gets set to the actual selected font. Maybe we shouldn't do that, but it seemed like a sensible default at the time.

> And I'm not shure that Font Manager treats properly such fonts as Dingbats and Kacst. It does not show symbols.

It definitely doesn't...
I'm not sure what the best approach to that is yet, so I keep kicking that can down the road. But it definitely needs to be fixed by 1.0

I'm going to leave this issue open as a reminder, hopefully motivator, about these issues.

Thanks for your interest.

**Comment by JerryCasiano** [comment]
This feature is implemented in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by JerryCasiano** [comment]
Closing this out as changes from testing were merged into master.
