### ISSUE TITLE
Where are fonts installed?

### ISSUE THREAD

**Issue by NatoBoram** [FontManager/master#49]
Hello! Being relatively new to Ubuntu, I needed a solution to install [large quantities of fonts](https://github.com/google/fonts/archive/master.zip) in Ubuntu and Font Manager helped me install a `.zip` with thousands of fonts, so I'm really thankful for that!

However, I wanted to see... _Where are those fonts installed?_

I read the `man font-manager` entry, but it's as good as empty. I tried to look into `~/fonts/`, but the folder doesn't exist and `/usr/local/share/fonts` is empty. Am I missing something?

**Comment by JerryCasiano** [comment]
Yes. The manpage certainly needs improvement.

~/.fonts is deprecated as has been for quite some time. It is still honored but that may not always be the case.

The new location is at ~/.local/share/fonts and this is where Font Manager installs font files. It will also only allow removal of fonts installed in that directory.

The files installed there by the application will be sorted first by type then by vendor and family.

HTH

**Comment by nbeaver** [comment]
Related: https://github.com/FontManager/master/issues/42

**Comment by NatoBoram** [comment]
Thanks!
