### ISSUE TITLE
AppData file wasn't updated when the desktop id was changed

### ISSUE THREAD

**Issue by hughsie** [FontManager/master#5]
Hi,

The AppData file has <id type="desktop">font-manager.desktop</id> but the desktop file is now named org.gnome.FontManager.desktop

Could you please update the <id> line in the appdata file, and optionally also rename the AppData file to have the same prefix as the desktop file (e.g. org.gnome.FontManager.appdata.xml) -- thanks.

**Comment by JerryCasiano** [comment]
Done. Thanks for pointing that out.
