### ISSUE TITLE
Feature request: in "Search Families", hide non-matching fonts

### ISSUE THREAD

**Issue by nbeaver** [FontManager/master#51]
I really like the incremental search in the "Search Families" box, but I find it confusing when it still shows all the non-matching font families as well.

![example-search](https://user-images.githubusercontent.com/3036798/35113006-98ce92ee-fc45-11e7-8aa6-f42b8fdfe699.png)

**Comment by JerryCasiano** [comment]
This feature is implemented in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by nbeaver** [comment]
Looks great! Should I close it now or wait until it's in master?

**Comment by JerryCasiano** [comment]
We can leave it open till it releases.

That way, if there are any other suggestions related to these changes we can get them sorted out here.

Thanks for checking it out!

**Comment by JerryCasiano** [comment]
This is fixed in master.

Thank you for your suggestions.
