### ISSUE TITLE
Feature request: in "Search Families", press "Enter" to advance to next match

### ISSUE THREAD

**Issue by nbeaver** [FontManager/master#52]
The Gtk.SearchEntry() "Search Families" box does not appear to have a way to jump to the next match when there are multiple matches. If this is intended behavior and not something going wrong on my end, I request that pressing "Enter" would advance to the next match.

**Comment by JerryCasiano** [comment]
This feature is implemented in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by nbeaver** [comment]
Hm, sometimes pressing enter checks/unchecks the box, and sometimes it jumps to the next match.

When I filed this feature request, I didn't realize that the down arrow key does this already. After trying it out, I think I prefer the up/down arrows to the enter key.

**Comment by JerryCasiano** [comment]
> Hm, sometimes pressing enter checks/unchecks the box, and sometimes it jumps to the next match.

That means your focus was on the list itself and not the entry.

> When I filed this feature request, I didn't realize that the down arrow key does this already. After trying it out, I think I prefer the up/down arrows to the enter key.

We can always disable that handler, not a big deal.

For now, you can open [Fontlist.vala](https://github.com/FontManager/master/blob/testing/src/font-manager/FontList.vala) and comment out lines 127 through 129.

**Comment by JerryCasiano** [comment]
This is fixed in master.

Thank you for your suggestions.
