### ISSUE TITLE
Feature request: in "Search Families", support non-prefix matches

### ISSUE THREAD

**Issue by nbeaver** [FontManager/master#53]
Currently, "Search Families" only matches the search text by prefix. For example, if the search text is "Symbol", it will match "Symbola", but not "OpenSymbol" or "Standard Symbols L".

This has many use cases, such as searching for font names containing e.g. "Mono" or "Arabic" but not starting with those terms.

**Comment by JerryCasiano** [comment]
I like all three of your suggestions. They make perfect sense and would add a lot of polish.

Currently we don't do anything when it comes to search, it's simply the default provided by GtkTreeView. In the future, the plan is to allow search based on any fields in the database and save the results to a "smart collection" but that's probably a ways off.

I appreciate your suggestions and will keep these issues open as a reminder/motivator.

Thanks!

**Comment by JerryCasiano** [comment]
This feature is implemented in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by nbeaver** [comment]
I can confirm the feature works as I expected.

**Comment by JerryCasiano** [comment]
This is fixed in master.

Thank you for your suggestions.
