### ISSUE TITLE
Improve Unicode Block list

### ISSUE THREAD

**Issue by RalphCorderoy** [FontManager/master#57]
When viewing a font, the Unicode Block list tells me there's 127 possible glyphs in Basic Latin's definition, etc.  IOW, these numbers don't change.  What I'd like to know is which of the blocks have glyphs in this font.  I'd be happy if the other blocks weren't in the list, or perhaps just greyed out so cursor-key focus skipped them, or hidden with a checkbox, ...  And the number, 127, could be 63/127 showing 63 of the possible 127 glyphs are provided by the font.

This would make it a lot easier to select a font and see it's basically supplying Thai, say.

fc-query on a font's file will show me a bitmap so I know U+20xx has some glyphs, but I have to hunt blocks that cover that in the list to see the glyphs.  If each block name was preceded by the code-point of its first glyph, e.g. '0400' for Cyrillic, then finding 20xx would be easier as the list is already sorted by this AIUI.

**Comment by JerryCasiano** [comment]
I'm sorry to say that the sidebar area where you can select different blocks/scripts may not even be there in the next release, not sure about this yet. I don't think it's very useful for most people in its current incarnation anyway.

The character map itself will definitely still be there and will no longer display anything that isn't in the selected font.

Making it easier for users to find certain characters, fonts that contain certain characters, finding fonts by supported languages, etc. are definitely goals.

Improvements in this area of the application will come, but expect them to come slowly.

**Comment by JerryCasiano** [comment]
This request is affected by changes in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by JerryCasiano** [comment]
Closing this out as it no longer applies to master.
