### ISSUE TITLE
To be able to activate only one font of a lot fonts added through "Font Sources" [Feature request]

### ISSUE THREAD

**Issue by tebicap** [FontManager/master#58]
(I hope you understand my english)

I have a few folders whit a lot of fonts each one, I drag that folders to "Font Sources" and I can activate all fonts of this folders but I can't activate a single font. 
If one of my folders have 500 fonts and, after exploring, I want to activate only one or two, I have to activate all 500 fonts and this is a bad thing.
(I don't know if there is already a way to do it)

regards

**Comment by JerryCasiano** [comment]
Your English is perfectly fine. ;-)

No, what you're asking for is not really possible at this point. 

And there's no easy workaround right now, I don't think..

I understand what you're trying to do and it makes perfect sense, there should be a way to do that. But not really in the context of Font Sources.

So I think we'll have to make it easy to install fonts from a source right in the font list. That way you if you only want one or two you could right click, select install and either disable or remove it later.

If that sounds like it would help, let me know and I'll try to work it into the next release.

**Comment by tebicap** [comment]
Yea!, I think that is the way too. Thank for answer.
In addition (although less important), it would be great to filter by folder source wen browsing or manage. So we could view the specific folder content as well as add all them to a collection.

**Comment by JerryCasiano** [comment]
>  it would be great to filter by folder source wen browsing or manage. So we could view the specific folder content as well as add all them to a collection.

Agreed.  I'll either add categories for each Source or make it easy to filter them through search.

Not sure when the next release will be, but it will be sometime this year and this will be addressed.

Thanks for the feedback.

**Comment by JerryCasiano** [comment]
I feel this is completed in master.

Any search which begins with / will match based on filepath.

Typing entire filepath is not necessary, just a portion of it is fine.

Closing this out now. Feel free to reopen if it doesn't resolve your issue.

Thanks.
