### ISSUE TITLE
How to add fonts to a "collection"?

### ISSUE THREAD

**Issue by twisp007** [FontManager/master#59]
How do these "collections" work? I can create a collection with a name but that's as far as I cloud go. Any documentation?

**Comment by JerryCasiano** [comment]
Sorry. No documentation yet. 

Collections are just a way to group/sort fonts, they make it easy to, for example, enable/disable a group fonts all at once. They don't change anything on disk.

I haven't reimplemented exporting yet but in the near future they'll also make it easy to archive/copy groups of fonts.

As far as how to use, after you've created a collection and given it a name just start dragging fonts to it from the list while in category view.

Hope that helps. If you have any other questions, related to collections or otherwise, feel to free to ask here.

Thanks for your interest.

**Comment by JerryCasiano** [comment]
This is fixed in master.

Added help documents.

**Comment by akvadrako** [comment]
I see now when you start dragging a font, the sidebar switches to show the collections. This is quite unintuitive - I had to find this issue before I could figure it out.

**Comment by JerryCasiano** [comment]
> I see now when you start dragging a font, the sidebar switches to show the collections. This is quite unintuitive - I had to find this issue before I could figure it out.

If you don't have help documents available, you're running a pretty outdated version.

The latest version doesn't even require you to open help, there's an inline help icon that goes over this particular quirk.

I've been keeping track and so far five people have commented on this design being unintuitive, obviously we would need to multiply that by some unknown to account for those who don't speak up. But it seems it's not a huge concern.

That said, it might get reworked for Gtk4 to a more traditional layout with both categories and collections in the same tree.

Thanks for the feedback.

**Comment by stkurz** [comment]
> …  some unknown to account for those who don't speak up

Count me in on having not found the feature without asking around! 

But perhaps this is also a question of the user base and who does what and expects font-manager to solve which particular issues. 

Is there a way to find out about actual usage statistics of font-manager (and, perhaps, of its features)?

**Comment by akvadrako** [comment]
@JerryCasiano Thanks, I am using 0.7.3, the current Ubuntu version. Indeed, help is not implemented.

**Comment by JerryCasiano** [comment]
@akvadrako 

I would strongly suggest purging the upstream Ubuntu packages and switching to the PPA unless you're on an old Ubuntu release.

The PPA supports the last two releases and will get you a much better experience.

@stkurz 

Alright... So (6 * ?) it is then. :-D

No, unfortunately I can't really think of a way to gather that type of feedback automatically.

Adding telemetry is definitely NOT an option in my opinion.

But even if it were, it wouldn't get us this type of data anyway, I don't think there's any way to reliably detect that a user is struggling with some part of the interface without actual user testing.

The problem for me in regards to this particular issue is that even if I consolidate both categories and collections into the same tree the way it's traditionally done, I don't see how that actually resolves the issue where a user doesn't realize that they should drag fonts into a collection. I'm my mind, all it does is clutter the sidebar for no real benefit.

Also, for better or worse, there's a lot of experimentation / iteration going on in our user interface with stuff that isn't always obvious and does require exploration on the part of the user.

If anybody has ideas, mockups or whatever that could improve usability. I'm definitely open to suggestions, the pros just need to outweigh the cons.

Thanks.

**Comment by akvadrako** [comment]
Personally, I think I would have figured it out if the collections were visible. Another thing I would expect is to be able to right-click on fonts and say "Add to collection > ...", but that's quite cumbersome.

The only thing I would recommend is showing both collections and categories at all times, but in separate panes, one above the other.

**Comment by JerryCasiano** [comment]
> The only thing I would recommend is showing both collections and categories at all times, but in separate panes, one above the other.

I'll do that in the Gtk4 version, which is already in progress.

**Comment by JerryCasiano** [comment]
@akvadrako 
@stkurz 

Your suggestion is now implemented in master.

Thanks.

P.S. Gtk4 port is on pause till the dust settles so no sense in waiting.
