### ISSUE TITLE
headerbar too big

### ISSUE THREAD

**Issue by corebots** [FontManager/master#6]
I'm using your app under Fedora23 (GNOME 3.17.92), installed from Software. The headerbar + its buttons are huge when compared to nautilus. 
screenshot: http://i.imgur.com/6sabVND.png

**Comment by JerryCasiano** [comment]
Interesting. Sorry but not on 23 yet. No idea when I'll get around to updating. If you're willing to help troubleshoot that would be appreciated.

Are there any warnings if you run in terminal with -d flag?

If you are willing to recompile, you could edit src/UX/Controls/Titlebar.vala and start by commenting out the line that adds menubar styling. I suspect that may be the cause, ironic since it was originally added to make the headerbar as compact as possible.

 Anyway, thanks for pointing this out.

**Comment by corebots** [comment]
I'm not that skilled with compiling, I've installed from GNOME Software. But if I run from terminal with -d, this is the output:
bash-4.3$ font-manager -d
[WARNING 10:06:08] [GLib-GObject] The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
[WARNING 10:06:08] [GLib-GObject] The property GtkMisc:ypad is deprecated and shouldn't be used anymore. It will be removed in a future version.
[WARNING 10:06:08] [GLib-GObject] The property GtkAlignment:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
[WARNING 10:06:08] [GLib-GObject] The property GtkAlignment:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
[DEBUG 10:06:08] [Gtk] Connecting to session manager
[INFO 10:06:08] [Logger:33] Font Manager 0.7.2
[INFO 10:06:08] [Logger:34] Using GLib 2.45.8
[INFO 10:06:08] [Logger:35] Using JSON-GLib 1.0.4
[INFO 10:06:08] [Logger:36] Using SQLite 3.8.11
[INFO 10:06:08] [Logger:37] Using FontConfig 2.11.94
[INFO 10:06:08] [Logger:38] Using Pango 1.37.5
[INFO 10:06:08] [Logger:39] Using GTK+ 3.17.6
[INFO 10:06:08] [Logger:41] Running on GNOME Shell 3.17.92

**Comment by JerryCasiano** [comment]
Sorry, but I assumed Fedora 23 had already released. It doesn't officially release till the end of next month. 

Feel free to re-open this if this is still an issue with the actual release.

**Comment by corebots** [comment]
OK thanks

**Comment by JerryCasiano** [comment]
Just got around to updating to 23 and also noticed this. Seems to only be an issue with Adwaita though. In any case, very ugly. 

This should be fixed in master.

Thanks again.
