### ISSUE TITLE
Copr for Fedora 28

### ISSUE THREAD

**Issue by xasx** [FontManager/master#60]
Is it possible to get an updated Copr repo for Fedora 28?

Could I trigger builds (how?) to do so or are there any preparations needed beforehand?

**Comment by JerryCasiano** [comment]
> Is it possible to get an updated Copr repo for Fedora 28?

Of course. I'll trigger an update today or tomorrow at the latest.

> Could I trigger builds (how?) to do so or are there any preparations needed beforehand?

I'm not sure about this actually.

I usually upload a source rpm, but there is no reason it couldn't use the last one. I'll have to check that when I get some time, not sure if COPR allows that or not. I think Launchpad does.

**Comment by JerryCasiano** [comment]
Done.

**Comment by xasx** [comment]
Thank you very much. :heart:
