### ISSUE TITLE
Settings saved to file using user's locale 

### ISSUE THREAD

**Issue by chrjen** [FontManager/master#64]
This is with Font Manager 0.7.3

Navigating to Settings > Display then hitting save gives the following error.

> Fontconfig error: "/home/chrjen/.config/fontconfig/conf.d/19-DisplayProperties.conf", line 13: "1,0": not a valid double
> Fontconfig error: "/home/chrjen/.config/fontconfig/conf.d/19-DisplayProperties.conf", line 16: "96,0": not a valid double

The issue here is that your program saves using a comma and not a period, probably a locale issue. You should format all numbers according to en_US local when writing to the file.

**Comment by JerryCasiano** [comment]
Ha! Never even considered that...

Thanks for reporting this!

Working on 0.7.4 at this time. I'll make sure this gets addressed before release.
