### ISSUE TITLE
Compilation error : undeclared FC_WEIGHT_DEMILIGHT                         ^

### ISSUE THREAD

**Issue by KMe0w** [FontManager/master#67]
`font-manager-fontconfig.c:700:35: error: ‘FC_WEIGHT_DEMILIGHT’ undeclared (first use in this function)
 #define LIGHT ((FC_WEIGHT_LIGHT + FC_WEIGHT_DEMILIGHT) / 2)
                                   ^
`

**Comment by JerryCasiano** [comment]
No offense, but what exactly am I supposed to do with this?

You've told me nothing that would allow me to even try to reproduce your issue...

**Comment by JerryCasiano** [comment]
Oh, I see your pull request now, what a stupid way of communicating with someone.

**Comment by JerryCasiano** [comment]
Duplicate of issue #3
