### ISSUE TITLE
font-manager man manual: the XDG variable names false

### ISSUE THREAD

**Issue by gnanet** [FontManager/master#71]
I had long hour, with unsuccessful search of my "user" fonts, i realized the deprecation of `.font` folder, but my `env` missed any of the XDG\_\*\_DIR, only contained XDG\_\*\_DIRS:

```
FILES
       $XDG_DATA_DIR/fonts
              Default user font directory.

       $XDG_CACHE_DIR/font-manager
              Application data which can safely be deleted.

       $XDG_CONFIG_DIR/font-manager
              Application specific configuration files.

       $XDG_CONFIG_DIR/fontconfig/conf.d
              Generated fontconfig configuration files.

       $XDG_CONFIG_DIR/dconf/user
              User interface preferences.
```

 So i did some RTFM, and realized there is a bug in the manual.

Official Freedesktop [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) states the variable names 

` a single base directory relative to which user-specific`  end with _HOME
`a set of preference ordered base directories` end with _DIRS

This means, the variables in the man manual above, should be like following:

```
FILES
       $XDG_DATA_HOME/fonts
              Default user font directory.

       $XDG_CACHE_HOME/font-manager
              Application data which can safely be deleted.

       $XDG_CONFIG_HOME/font-manager
              Application specific configuration files.

       $XDG_CONFIG_HOME/fontconfig/conf.d
              Generated fontconfig configuration files.

       $XDG_CONFIG_HOME/dconf/user
              User interface preferences.
```

**Comment by JerryCasiano** [comment]
Thanks for pointing this out.
