### ISSUE TITLE
Please post full version in release tarballs

### ISSUE THREAD

**Issue by alerque** [FontManager/master#72]
The release tarballs should have the full version number in the filename, not a truncated version without the hotfix number. The current practice makes packaging for distros complicated because the same filename starts coming in with a different checksum.

**Comment by JerryCasiano** [comment]
Thanks for pointing this out.

I'll address this later today.

**Comment by JerryCasiano** [comment]
Seems less than ideal to add another number to the version but it'll have to do for now as bumping the version to 0.7.5 so quickly for such minor changes also feels wrong.

In any case, thanks again and please let me know if you run into any other issues.

**Comment by alerque** [comment]
Thanks! That will do nicely — packaging with just one version number and without having to shuffle files for different versions out of the way is a lot simpler. I've updated the Arch Linux AUR packaging to 0.7.4.3.

**Comment by JerryCasiano** [comment]
Good to hear.

And thank you for maintaining the Arch package.

**Comment by JerryCasiano** [comment]
Oh BTW.

You should drop libgee from the dependencies.

file-roller is also no longer a build dependency - it will be used if it's available at runtime, if not the application will log a message suggesting installation.

**Comment by alerque** [comment]
Done, thanks for the tip.
