### ISSUE TITLE
flatpak support

### ISSUE THREAD

**Issue by corebots** [FontManager/master#73]
Hi, please can you make a flatpak and add your nice app to flathub? https://flathub.org/home or perhaps a F30 version on copr? thank you

**Comment by JerryCasiano** [comment]
> Hi, please can you make a flatpak and add your nice app to flathub? https://flathub.org/home or perhaps a F30 version on copr? thank you

No. Sorry, not interested in doing that right now.

Feel free to submit a pull request that does this though, as long as it works properly I'll be happy to merge it.

Thanks!

**Comment by corebots** [comment]
thank your for the f30 repo!

**Comment by JerryCasiano** [comment]
Of course. Your welcome.

I didn't think F30 was even a target yet so thanks for pointing it out.

I've automated the builds and set them to track Fedora branching so hopefully it picks new targets up automatically in the future.

**Comment by wolfv** [comment]
This spec (sve as `org.jerrycasiano.FontManager.json`)

```json
{
    "app-id": "org.jerrycasiano.FontManager",
    "runtime": "org.gnome.Platform",
    "runtime-version": "3.34",
    "sdk": "org.gnome.Sdk",
    "command": "font-manager",
    "finish-args": [
        /* X11 + XShm access */
        "--share=ipc", "--socket=x11",
        /* Wayland access */
        "--socket=wayland",
        /* Needs to talk to the network: */
        "--share=network",
        /* Needs to save files locally */
        "--filesystem=xdg-documents",
        "--socket=session-bus"
        /* "--filesystem=home"  might be necessary for ~/.local/share/fonts/ ? */
    ],
    "modules": [
		{
            "name": "font-manager",
            "buildsystem": "meson",
            "config-opts": [ ],
            "sources": [
                {
                    "type": "git",
                    "url": "https://github.com/FontManager/font-manager.git"
                }
            ]
        }
    ]
}
```

seems to work quite fine (last release doesn't build due to some vala problem).

```
# Build:
flatpak-builder build-dir org.jerrycasiano.FontManager.json
# Test run:
flatpak-builder --run build-dir org.jerrycasiano.FontManager.json font-manager
```

**Comment by JerryCasiano** [comment]
> seems to work quite fine 

I don't see how it possibly could. As far as I know nothing has really changed in regards to the way Flatpak deals with fonts or their configuration. Even if we are allowed to modify the users actual configuration files I don't think the interface would reflect that on the next start and that's a deal breaker.

But I will check again when I get some time.

**Comment by wolfv** [comment]
yeah, it's true that fontmanager might not automatically display all available fonts.
but manually adding folders from the home dir works (e.g. i added `~/.local/share/fonts`)

depending on the permissions set (can set to filesystem host) then you could do anything (also defeats the purpose of sandboxing), but at least distribution is very nice! :)
