### ISSUE TITLE
Invalid valac version check

### ISSUE THREAD

**Issue by Soft** [FontManager/master#8]
I was looking through the configure.ac script for FontManager and I have a feeling the version check for valac might be broken. The relevant bits are here:

```
AM_PROG_VALAC(
    [0.24],
    dnl Gtk.TextBuffer API break
    [AM_PROG_VALAC(
        [0.27.1],
        [AC_SUBST(VALA_0271_OR_LATER, [" -D VALA_0271_OR_LATER"])],
        [:]
    )],
    AC_MSG_ERROR([

    Build requirements (valac) were not met:

    Please install Vala >= 0.24 and try again.

    https://wiki.gnome.org/Projects/Vala

    ])
)
```
If my understanding of autotools semantics is correct, if the initial check for the compiler with minimum version of 0.24 succeeds the VALAC variable is set to point to the compiler. After this, the script does a second check for the version 0.27.1 and reacts accordingly.

The bug happens if the initial check succeeds but the second check fails. In this case, the correct path to the initially found valac compiler is replaced with the generic string "valac" which might not be the right one. For example, in my system the binary for valac version 0.24 is called valac-0.24 and this bug breaks the compilation for me.

**Comment by JerryCasiano** [comment]
Thanks for pointing this out. 

Can you try again with the latest commit. It checks for the higher version first.

**Comment by Soft** [comment]
Yeah, this seems to have fixed the problem for me. Thanks!
