### ISSUE TITLE
Build fails when HAVE_FILE_ROLLER undefined

### ISSUE THREAD

**Issue by Soft** [FontManager/master#9]
If I understand correctly file-roller should now be an optional dependency in FontManager. However, when building with HAVE_FILE_ROLLER undefined the build fail because of missing `ifdef` in [FileSelector](https://github.com/FontManager/master/blob/master/src/UX/Dialogs/FileSelector.vala#L59). This happens because ArchiveManager itself is correctly enclosed in `ìfdef` and not present in the build. Bellow are the relevant error messages from my system:

```
./UX/Dialogs/FileSelector.vala:59.39-59.52: error: The name `ArchiveManager' does not exist in the context of `FontMan
ager.FileSelector.run_install'
            var archive_manager = new ArchiveManager();
                                      ^^^^^^^^^^^^^^
./UX/Dialogs/FileSelector.vala:59.17-59.54: error: var declaration not allowed with non-typed initializer
            var archive_manager = new ArchiveManager();
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
./UX/Dialogs/FileSelector.vala:60.38-60.52: error: The name `archive_manager' does not exist in the context of `FontMa
nager.FileSelector.run_install'
            foreach (var mimetype in archive_manager.get_supported_types())
```

**Comment by JerryCasiano** [comment]
Thanks again. Should be good in master.
